name: Self-Hosted DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Rebuild and Run Docker Containers
        shell: cmd
        run: |
          docker compose down
          docker compose up --build -d
